[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config]
basedpyright.analysis.stubPath = "${HOME}/.local/share/helix/pyright-stubs/"
basedpyright.analysis.typeCheckingMode = "standard"
basedpyright.analysis.autoImportCompletion = false

[language-server.ruff]
command = "ruff"
args = ["server", "-q", "--preview"]

[language-server.rust-analyzer]
timeout = 60

[language-server.rust-analyzer.config]
check.command = "clippy"

[[language]]
name = "python"
language-servers = ["basedpyright", "ruff"]

