[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
stubPath = "${HOME}/.local/share/helix/pyright-stubs"

[language-server.rust-analyzer]
timeout = 60

[language-server.rust-analyzer.config]
check.command = "clippy"

[[language]]
name = "python"
language-servers = ["pyright"]

